package com.pma.running.model;

public enum NotificationType {
    FRIENDSHIP_REQUEST, APPROVED_FRIENDSHIP,
    COMMENT_ON_POST, LIKE_ON_POST,
    ACTIVITY_REQUEST, APPROVED_ACTIVITY_REQUEST, REJECTED_ACTIVITY_REQUEST
}
